### ISSUE TITLE
Arduino IDE Library specification rev.2.1 will be implemented starting from version 1.6.10

### ISSUE THREAD

**Issue by herb42** [pololu/zumo-shield#3]
Hi,
Will not install library, error "Zip doesn't contain a library".
The files are there, but the zip file does not conform to the new specification:
"Arduino IDE Library specification rev.2.1 will be implemented starting from version 1.6.10"
Would appreciate the zip file to be restructured.

**Comment by ietcybermax** [comment]
Hi herb, the same problem. i have Zumo robot for arduino, v1.2 but the same error "Zip doesn't contain a library", also i tried download from arduino repository in 'library manager' but not. 😞

**Comment by sderoy** [comment]
any up-date dosent work ,,,,,,

**Comment by DavidEGrayson** [comment]
You should follow the installation instructions we have written in this repository's [README file](https://github.com/pololu/zumo-shield).  If that does not work for you, you should post all the details of what you did and what went wrong and we'll probably be able to help you figure it out.
